import * as chromeLauncher from "chrome-launcher";
import lighthouse from "lighthouse";
import { postSigned } from "../../shared/signing.js";
import type { FlowEvent, JobRequest, ToolResult } from "../../shared/types.js";

interface Finding {
  id: string;
  title: string;
  score: number | null;
  description: string;
}

interface MaxData {
  seo_score: number;
  findings: Finding[];
  suggestions: string[];
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});

async function main(): Promise<void> {
  const brief = parseBrief();
  const secret = requiredEnv("JOB_HMAC_SECRET");
  const url = String(brief.brief.url || "");
  if (!url) throw new Error("Max requires brief.url");

  const send = async (event: FlowEvent) => emit(brief, secret, { event });
  await send({ event: "activate", step: "report" });
  await send({ event: "data", step: "report", patch: emptyReportData(url) });
  await send({ event: "progress", step: "report", n: 1 });
  await send({ event: "log", step: "report", kind: "cmd", text: `max audit ${url}` });

  const chrome = await chromeLauncher.launch({
    chromePath: process.env.CHROME_PATH || process.env.CHROME_BIN,
    chromeFlags: ["--headless=new", "--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu"],
  });

  try {
    await send({ event: "progress", step: "report", n: 2 });
    const runner = await lighthouse(
      url,
      {
        port: chrome.port,
        output: "json",
        logLevel: "error",
        onlyCategories: ["seo"],
      },
      undefined,
    );

    if (!runner?.lhr) throw new Error("Lighthouse did not return a report");

    const seoScore = Math.round((runner.lhr.categories.seo?.score ?? 0) * 100);
    const findings = collectFindings(runner.lhr.audits);
    const suggestions = suggestionsFromFindings(findings);
    const data: MaxData = { seo_score: seoScore, findings, suggestions };

    await send({
      event: "data",
      step: "report",
      patch: reportData(url, data),
    });
    await send({ event: "progress", step: "report", n: 3 });
    await send({ event: "progress", step: "report", n: 4 });
    await send({ event: "progress", step: "report", n: 5 });
    await send({ event: "complete", step: "report" });

    const result: ToolResult<MaxData> = {
      ok: true,
      tool: "max",
      command: "audit",
      data,
      error: null,
      meta: {
        lighthouse_version: runner.lhr.lighthouseVersion,
        final_url: runner.lhr.finalDisplayedUrl || runner.lhr.finalUrl,
        generated_at: new Date().toISOString(),
      },
    };
    await emit(brief, secret, { result });
  } finally {
    await chrome.kill();
  }
}

async function emit(
  brief: JobRequest,
  secret: string,
  payload: { event?: FlowEvent; result?: ToolResult<MaxData> },
): Promise<void> {
  const envelope = { job_id: brief.job_id, ...payload };
  process.stdout.write(`${JSON.stringify(envelope)}\n`);
  await postSigned(brief.callback_url, secret, envelope);
}

function collectFindings(audits: Record<string, any>): Finding[] {
  return Object.entries(audits)
    .filter(([, audit]) => {
      if (audit.score === null || audit.scoreDisplayMode === "notApplicable") return false;
      return typeof audit.score === "number" && audit.score < 1;
    })
    .slice(0, 6)
    .map(([id, audit]) => ({
      id,
      title: audit.title,
      score: audit.score,
      description: stripMarkup(audit.description || ""),
    }));
}

function suggestionsFromFindings(findings: Finding[]): string[] {
  if (!findings.length) return ["Keep metadata and structured content current as products change."];

  return findings.slice(0, 5).map((finding) => {
    if (finding.id.includes("meta-description")) return "Tighten the homepage meta description around custom basketball jerseys and team uniforms.";
    if (finding.id.includes("document-title")) return "Keep the page title specific to custom basketball jerseys.";
    if (finding.id.includes("crawlable")) return "Ensure all product cards and quote links are crawlable anchor elements.";
    if (finding.id.includes("hreflang")) return "Add hreflang only if localized versions launch.";
    if (finding.id.includes("canonical")) return "Add a canonical URL once the final production domain is selected.";
    return `Address Lighthouse SEO audit: ${finding.title}.`;
  });
}

function reportData(url: string, data: MaxData): Record<string, unknown> {
  const issueCount = data.findings.length;
  return {
    eyebrow: "Lighthouse SEO audit",
    heading: "custombasketball — SEO handoff",
    meta: ["Generated by Max", new URL(url).hostname, `${issueCount} issues`],
    doneLabel: "Handed to Maestro",
    kpis: [
      { value: data.seo_score, suffix: "%", label: "SEO score" },
      { value: issueCount, label: "Issues found" },
      { value: data.suggestions.length, label: "Fixes proposed" },
    ],
    chart: chartFromScore(data.seo_score, issueCount),
  };
}

function emptyReportData(url: string): Record<string, unknown> {
  return {
    eyebrow: "Lighthouse SEO audit",
    heading: "Auditing custombasketball",
    meta: ["Running in Max", new URL(url).hostname, "Waiting for Lighthouse"],
    doneLabel: "Handed to Maestro",
    kpis: [
      { value: 0, suffix: "%", label: "SEO score" },
      { value: 0, label: "Issues found" },
      { value: 0, label: "Fixes proposed" },
    ],
    chart: [16, 18, 20, 18, 16, 20],
  };
}

function chartFromScore(score: number, issueCount: number): number[] {
  const base = Math.max(12, score);
  return [base * 0.45, base * 0.58, base * 0.67, base * 0.82, base * 0.9, Math.max(18, 100 - issueCount * 8)].map((n) =>
    Math.round(Math.min(96, n)),
  );
}

function stripMarkup(text: string): string {
  return text.replace(/\[[^\]]+\]\([^)]+\)/g, "").replace(/\s+/g, " ").trim();
}

function parseBrief(): JobRequest {
  const raw = flagValue("--brief");
  return JSON.parse(raw) as JobRequest;
}

function flagValue(name: string): string {
  const index = process.argv.indexOf(name);
  if (index === -1 || index === process.argv.length - 1) throw new Error(`missing ${name}`);
  return process.argv[index + 1];
}

function requiredEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}
